trigger:
  branches:
    include:
      - backend

pool:
  name: Default
  demands:
    - agent.name -equals SelfHosted-Backend

variables:
- group: backend-env-vars

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '24.x'
    displayName: 'Use Node.js 24'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - task: AzureAppServiceSettings@1
    displayName: 'Configure App Service Settings'
    inputs:
      azureSubscription: 'Azure-Service-Connection'
      appName: 'rg-opulanz-backend'
      appSettings: |
        [
          { "name": "PORT", "value": "$(PORT)" },
          { "name": "NODE_ENV", "value": "$(NODE_ENV)" },
          { "name": "DB_HOST", "value": "$(DB_HOST)" },
          { "name": "DB_USER", "value": "$(DB_USER)" },
          { "name": "DB_PASSWORD", "value": "$(DB_PASSWORD)" },
          { "name": "DB_NAME", "value": "$(DB_NAME)" },
          { "name": "DB_PORT", "value": "$(DB_PORT)" },
          { "name": "FRONTEND_URL", "value": "$(FRONTEND_URL)" },
          { "name": "NARVI_API_URL", "value": "$(NARVI_API_URL)" },
          { "name": "NARVI_API_KEY_ID", "value": "$(NARVI_API_KEY_ID)" },
          { "name": "EMAIL_USER", "value": "$(EMAIL_USER)" },
          { "name": "EMAIL_PASS", "value": "$(EMAIL_PASS)" }
        ]

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure App Service'
    inputs:
      azureSubscription: 'Azure-Service-Connection'
      appName: 'rg-opulanz-backend'
      package: '.'
